/**
 * Tabelas de campos por registro do Layout Folhamatic Fiscal v2.0.06.
 * Gerado a partir do PDF oficial. Não editar a mão — regenerar do PDF.
 */
import type { RecordSpec } from './iobSageLayout';

export const LAYOUT: Record<string, RecordSpec> = {
  E001: {
    registro: 'E001',
    descricao: 'IDENTIFICAÇÃO DA EMPRESA',
    obrigatorio: true,
    ocorrencia: 'uma vez por arquivo',
    descricao_geral: 'Identificação obrigatória da empresa para a qual os dados serão importados.',
    campos: [
      { ordem: 1, nome: 'NOME DO REGISTRO', descricao: 'Informe E001', tipo: 'A', tamanho: 4, decimais: null, posicao_inicial: 1, posicao_final: 4, obrigatorio: true, valor_fixo: 'E001', observacoes: '' },
      { ordem: 2, nome: 'NÚMERO DA EMPRESA', descricao: 'Número da empresa no E-Fiscal', tipo: 'N', tamanho: 4, decimais: null, posicao_inicial: 5, posicao_final: 8, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 3, nome: 'VERSÃO LAYOUT', descricao: 'Versão do layout', tipo: 'X', tamanho: 6, decimais: null, posicao_inicial: 9, posicao_final: 14, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 4, nome: 'CONTROLE DO SISTEMA', descricao: 'Informe 0', tipo: 'N', tamanho: 1, decimais: null, posicao_inicial: 15, posicao_final: 15, obrigatorio: true, valor_fixo: null, observacoes: '' },
    ],
  },
  E010: {
    registro: 'E010',
    descricao: 'CADASTRO DE CLIENTES/FORNECEDORES',
    obrigatorio: false,
    ocorrencia: 'múltiplos por arquivo',
    descricao_geral: 'Importa cadastro de clientes e fornecedores. Tamanho fixo 977.',
    campos: [
      { ordem: 1, nome: 'NOME DO REGISTRO', descricao: 'E010', tipo: 'A', tamanho: 4, decimais: null, posicao_inicial: 1, posicao_final: 4, obrigatorio: true, valor_fixo: 'E010', observacoes: '' },
      { ordem: 2, nome: 'CÓDIGO DO CLIENTE/FORNECEDOR', descricao: '', tipo: 'X', tamanho: 20, decimais: null, posicao_inicial: 5, posicao_final: 24, obrigatorio: true, valor_fixo: null, observacoes: '' },
      { ordem: 3, nome: 'NOME', descricao: '', tipo: 'X', tamanho: 100, decimais: null, posicao_inicial: 25, posicao_final: 124, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 4, nome: 'DATA DE INCLUSÃO', descricao: '', tipo: 'D', tamanho: 8, decimais: null, posicao_inicial: 125, posicao_final: 132, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 5, nome: 'TIPO DE LOGRADOURO', descricao: '', tipo: 'X', tamanho: 15, decimais: null, posicao_inicial: 133, posicao_final: 147, obrigatorio: true, valor_fixo: null, observacoes: '' },
      { ordem: 6, nome: 'LOGRADOURO', descricao: '', tipo: 'X', tamanho: 100, decimais: null, posicao_inicial: 148, posicao_final: 247, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 7, nome: 'NÚMERO DO LOGRADOURO', descricao: '', tipo: 'X', tamanho: 10, decimais: null, posicao_inicial: 248, posicao_final: 257, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 8, nome: 'COMPLEMENTO DO LOGRADOURO', descricao: '', tipo: 'X', tamanho: 50, decimais: null, posicao_inicial: 258, posicao_final: 307, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 9, nome: 'BAIRRO', descricao: '', tipo: 'X', tamanho: 30, decimais: null, posicao_inicial: 308, posicao_final: 337, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 10, nome: 'ESTADO', descricao: '', tipo: 'A', tamanho: 2, decimais: null, posicao_inicial: 338, posicao_final: 339, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 11, nome: 'CIDADE', descricao: '', tipo: 'N', tamanho: 7, decimais: null, posicao_inicial: 340, posicao_final: 346, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 12, nome: 'CEP', descricao: '', tipo: 'N', tamanho: 8, decimais: null, posicao_inicial: 347, posicao_final: 354, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 13, nome: 'PAÍS', descricao: '', tipo: 'N', tamanho: 5, decimais: null, posicao_inicial: 355, posicao_final: 359, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 14, nome: 'CNPJ/CPF', descricao: '', tipo: 'A', tamanho: 14, decimais: null, posicao_inicial: 360, posicao_final: 373, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 15, nome: 'INSCRIÇÃO ESTADUAL', descricao: '', tipo: 'X', tamanho: 18, decimais: null, posicao_inicial: 374, posicao_final: 391, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 16, nome: 'INSCRIÇÃO MUNICIPAL', descricao: '', tipo: 'A', tamanho: 14, decimais: null, posicao_inicial: 392, posicao_final: 405, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 17, nome: 'INSCRIÇÃO SUFRAMA', descricao: '', tipo: 'X', tamanho: 9, decimais: null, posicao_inicial: 406, posicao_final: 414, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 18, nome: 'CONTATO', descricao: '', tipo: 'X', tamanho: 35, decimais: null, posicao_inicial: 415, posicao_final: 449, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 19, nome: 'TELEFONE', descricao: '', tipo: 'X', tamanho: 16, decimais: null, posicao_inicial: 450, posicao_final: 465, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 20, nome: 'FAX', descricao: '', tipo: 'X', tamanho: 16, decimais: null, posicao_inicial: 466, posicao_final: 481, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 21, nome: 'DATA DA ALTERAÇÃO CADASTRAL NO SISTEMA E-FISCAL', descricao: '', tipo: 'D', tamanho: 8, decimais: null, posicao_inicial: 482, posicao_final: 489, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 22, nome: 'CLIENTE', descricao: '', tipo: 'A', tamanho: 1, decimais: null, posicao_inicial: 490, posicao_final: 490, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 23, nome: 'FORNECEDOR', descricao: '', tipo: 'A', tamanho: 1, decimais: null, posicao_inicial: 491, posicao_final: 491, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 24, nome: 'PRODUTOR RURAL', descricao: '', tipo: 'A', tamanho: 1, decimais: null, posicao_inicial: 492, posicao_final: 492, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 25, nome: 'FORNECEDOR SUBSTITUTO TRIBUTÁRIO', descricao: '', tipo: 'A', tamanho: 1, decimais: null, posicao_inicial: 493, posicao_final: 493, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 26, nome: 'SIMPLES NACIONAL', descricao: '', tipo: 'A', tamanho: 1, decimais: null, posicao_inicial: 494, posicao_final: 494, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 27, nome: 'INSCRITO NO MUNICÍPIO', descricao: '', tipo: 'A', tamanho: 1, decimais: null, posicao_inicial: 495, posicao_final: 495, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 28, nome: 'E-mail do Contato', descricao: '', tipo: 'A', tamanho: 100, decimais: null, posicao_inicial: 496, posicao_final: 595, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 29, nome: 'Endereço na web do site', descricao: '', tipo: 'A', tamanho: 100, decimais: null, posicao_inicial: 596, posicao_final: 695, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 30, nome: 'Hospedagem de sites e banco de dados', descricao: '', tipo: 'A', tamanho: 1, decimais: null, posicao_inicial: 696, posicao_final: 696, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 31, nome: 'Endereço IP do site', descricao: '', tipo: 'X', tamanho: 15, decimais: null, posicao_inicial: 697, posicao_final: 711, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 32, nome: 'Endereço na web do site (host)', descricao: '', tipo: 'X', tamanho: 100, decimais: null, posicao_inicial: 712, posicao_final: 811, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 33, nome: 'Data início do contrato', descricao: '', tipo: 'D', tamanho: 8, decimais: null, posicao_inicial: 812, posicao_final: 819, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 34, nome: 'Data final de contrato', descricao: '', tipo: 'D', tamanho: 8, decimais: null, posicao_inicial: 820, posicao_final: 827, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 35, nome: 'Gateway de pagamentos', descricao: '', tipo: 'A', tamanho: 1, decimais: null, posicao_inicial: 828, posicao_final: 828, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 36, nome: 'Data início contrato gateway', descricao: '', tipo: 'D', tamanho: 8, decimais: null, posicao_inicial: 829, posicao_final: 836, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 37, nome: 'Data final contrato gateway', descricao: '', tipo: 'D', tamanho: 8, decimais: null, posicao_inicial: 837, posicao_final: 844, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 38, nome: 'Provimentos de soluções', descricao: '', tipo: 'A', tamanho: 1, decimais: null, posicao_inicial: 845, posicao_final: 845, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 39, nome: 'IP site lojas virtuais', descricao: '', tipo: 'X', tamanho: 15, decimais: null, posicao_inicial: 846, posicao_final: 860, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 40, nome: 'Endereço web lojas virtuais', descricao: '', tipo: 'X', tamanho: 100, decimais: null, posicao_inicial: 861, posicao_final: 960, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 41, nome: 'Data início contrato lojas virtuais', descricao: '', tipo: 'D', tamanho: 8, decimais: null, posicao_inicial: 961, posicao_final: 968, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 42, nome: 'Data final contrato lojas virtuais', descricao: '', tipo: 'D', tamanho: 8, decimais: null, posicao_inicial: 969, posicao_final: 976, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 43, nome: 'CONTROLE DO SISTEMA', descricao: 'Informe 0', tipo: 'N', tamanho: 1, decimais: null, posicao_inicial: 977, posicao_final: 977, obrigatorio: true, valor_fixo: null, observacoes: '' },
    ],
  },
  E020: {
    registro: 'E020',
    descricao: 'CADASTRO DE PRODUTOS/SERVIÇOS',
    obrigatorio: false,
    ocorrencia: 'múltiplos por arquivo',
    descricao_geral: 'Cadastro de produtos/serviços. Tamanho fixo 486.',
    campos: [
      { ordem: 1, nome: 'NOME DO REGISTRO', descricao: '', tipo: 'A', tamanho: 4, decimais: null, posicao_inicial: 1, posicao_final: 4, obrigatorio: true, valor_fixo: 'E020', observacoes: '' },
      { ordem: 2, nome: 'CÓDIGO DO PRODUTO/SERVIÇO', descricao: '', tipo: 'X', tamanho: 14, decimais: null, posicao_inicial: 5, posicao_final: 18, obrigatorio: true, valor_fixo: null, observacoes: '' },
      { ordem: 3, nome: 'DESCRIÇÃO DO PRODUTO/SERVIÇO', descricao: '', tipo: 'X', tamanho: 60, decimais: null, posicao_inicial: 19, posicao_final: 78, obrigatorio: true, valor_fixo: null, observacoes: '' },
      { ordem: 4, nome: 'DATA DA INCLUSÃO DO PRODUTO/SERVIÇO', descricao: '', tipo: 'D', tamanho: 8, decimais: null, posicao_inicial: 79, posicao_final: 86, obrigatorio: true, valor_fixo: null, observacoes: '' },
      { ordem: 5, nome: 'DATA DA ALTERAÇÃO CADASTRAL NA DESCRIÇÃO', descricao: '', tipo: 'D', tamanho: 8, decimais: null, posicao_inicial: 87, posicao_final: 94, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 6, nome: 'PERÍODO INICIAL DE UTILIZAÇÃO DO PRODUTO/SERVIÇO', descricao: '', tipo: 'D', tamanho: 8, decimais: null, posicao_inicial: 95, posicao_final: 102, obrigatorio: true, valor_fixo: null, observacoes: '' },
      { ordem: 7, nome: 'PERÍODO FINAL DE UTILIZAÇÃO DO PRODUTO/SERVIÇO', descricao: '', tipo: 'D', tamanho: 8, decimais: null, posicao_inicial: 103, posicao_final: 110, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 8, nome: 'CÓDIGO ANTERIOR', descricao: '', tipo: 'X', tamanho: 14, decimais: null, posicao_inicial: 111, posicao_final: 124, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 9, nome: 'GÊNERO DO ITEM', descricao: '', tipo: 'A', tamanho: 2, decimais: null, posicao_inicial: 125, posicao_final: 126, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 10, nome: 'TIPO DO PRODUTO', descricao: '', tipo: 'A', tamanho: 2, decimais: null, posicao_inicial: 127, posicao_final: 128, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 11, nome: 'TIPO PARA O INVENTÁRIO', descricao: '', tipo: 'N', tamanho: 4, decimais: null, posicao_inicial: 129, posicao_final: 132, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 12, nome: 'NBM/SH', descricao: '', tipo: 'X', tamanho: 15, decimais: null, posicao_inicial: 133, posicao_final: 147, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 13, nome: 'CÓDIGO DE BARRA', descricao: '', tipo: 'X', tamanho: 100, decimais: null, posicao_inicial: 148, posicao_final: 247, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 14, nome: 'COMBUSTÍVEL/SOLVENTE', descricao: '', tipo: 'A', tamanho: 1, decimais: null, posicao_inicial: 248, posicao_final: 248, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 15, nome: 'CÓDIGO SEFAZ', descricao: '', tipo: 'A', tamanho: 4, decimais: null, posicao_inicial: 249, posicao_final: 252, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 16, nome: 'CÓDIGO ANP', descricao: '', tipo: 'A', tamanho: 9, decimais: null, posicao_inicial: 253, posicao_final: 261, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 17, nome: 'CÓD.UNID.COMERCIAL', descricao: '', tipo: 'X', tamanho: 6, decimais: null, posicao_inicial: 262, posicao_final: 267, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 18, nome: 'CÓD. UNID. ESTOQUE', descricao: '', tipo: 'X', tamanho: 6, decimais: null, posicao_inicial: 268, posicao_final: 273, obrigatorio: true, valor_fixo: null, observacoes: '' },
      { ordem: 19, nome: 'FATOR DE CONVERSÃO', descricao: '', tipo: 'N', tamanho: 14, decimais: 6, posicao_inicial: 274, posicao_final: 287, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 20, nome: 'CÓDIGO DO PRODUTO (DNF)', descricao: '', tipo: 'N', tamanho: 3, decimais: null, posicao_inicial: 288, posicao_final: 290, obrigatorio: true, valor_fixo: null, observacoes: '' },
      { ordem: 21, nome: 'FATOR DE CONV. PARA A UNID. MED. EST. (DNF)', descricao: '', tipo: 'N', tamanho: 14, decimais: 3, posicao_inicial: 291, posicao_final: 304, obrigatorio: true, valor_fixo: null, observacoes: '' },
      { ordem: 22, nome: 'CAPACIDADE VOLUMÉTRICA (ML)', descricao: '', tipo: 'N', tamanho: 5, decimais: null, posicao_inicial: 305, posicao_final: 309, obrigatorio: true, valor_fixo: null, observacoes: '' },
      { ordem: 23, nome: 'ALÍQ. IPI', descricao: '', tipo: 'N', tamanho: 5, decimais: 2, posicao_inicial: 310, posicao_final: 314, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 24, nome: 'SIT. TRIB. IPI', descricao: '', tipo: 'A', tamanho: 2, decimais: null, posicao_inicial: 315, posicao_final: 316, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 25, nome: 'SERVIÇOS LC 116/03', descricao: '', tipo: 'X', tamanho: 5, decimais: null, posicao_inicial: 317, posicao_final: 321, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 26, nome: 'CONTA ANALÍTICA CONTÁBIL', descricao: '', tipo: 'X', tamanho: 50, decimais: null, posicao_inicial: 322, posicao_final: 371, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 27, nome: 'ALÍQ. ICMS', descricao: '', tipo: 'N', tamanho: 7, decimais: 4, posicao_inicial: 372, posicao_final: 378, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 28, nome: 'ADICIONAL ALÍQ. ICMS', descricao: '', tipo: 'N', tamanho: 7, decimais: 4, posicao_inicial: 379, posicao_final: 385, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 29, nome: 'ADICIONAL ALÍQ. ICMS (RJ)', descricao: '', tipo: 'A', tamanho: 1, decimais: null, posicao_inicial: 386, posicao_final: 386, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 30, nome: '% RED. BASE CÁLC. ICMS', descricao: '', tipo: 'N', tamanho: 7, decimais: 4, posicao_inicial: 387, posicao_final: 393, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 31, nome: 'UNIT. BASE ICMS ST', descricao: '', tipo: 'N', tamanho: 14, decimais: 2, posicao_inicial: 394, posicao_final: 407, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 32, nome: 'SIT.TRIB. ICMS TAB. A', descricao: '', tipo: 'A', tamanho: 1, decimais: null, posicao_inicial: 408, posicao_final: 408, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 33, nome: 'SIT.TRIB. ICMS TAB. B', descricao: '', tipo: 'A', tamanho: 2, decimais: null, posicao_inicial: 409, posicao_final: 410, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 34, nome: 'SIT. TRIB. PIS', descricao: '', tipo: 'A', tamanho: 2, decimais: null, posicao_inicial: 411, posicao_final: 412, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 35, nome: 'SIT. TRIB. COFINS', descricao: '', tipo: 'A', tamanho: 2, decimais: null, posicao_inicial: 413, posicao_final: 414, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 36, nome: 'TIPO DE INCIDÊNCIA', descricao: '', tipo: 'A', tamanho: 1, decimais: null, posicao_inicial: 415, posicao_final: 415, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 37, nome: 'TABELA BEBIDAS FRIAS ANEXO III', descricao: '', tipo: 'A', tamanho: 3, decimais: null, posicao_inicial: 416, posicao_final: 418, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 38, nome: 'CÓDIGO DO GRUPO', descricao: '', tipo: 'A', tamanho: 2, decimais: null, posicao_inicial: 419, posicao_final: 420, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 39, nome: 'MARCA COMERCIAL', descricao: '', tipo: 'A', tamanho: 60, decimais: null, posicao_inicial: 421, posicao_final: 480, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 40, nome: 'CÓDIGO SEFAZ MG', descricao: '', tipo: 'A', tamanho: 5, decimais: null, posicao_inicial: 481, posicao_final: 485, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 41, nome: 'CONTROLE DO SISTEMA', descricao: 'Informe 0', tipo: 'N', tamanho: 1, decimais: null, posicao_inicial: 486, posicao_final: 486, obrigatorio: true, valor_fixo: null, observacoes: '' },
    ],
  },
  E200: {
    registro: 'E200',
    descricao: 'NOTAS FISCAIS',
    obrigatorio: false,
    ocorrencia: 'um por nota fiscal',
    descricao_geral: 'Cabeçalho da nota fiscal. Tamanho fixo 422.',
    campos: [
      { ordem: 1, nome: 'NOME DO REGISTRO', descricao: '', tipo: 'A', tamanho: 4, decimais: null, posicao_inicial: 1, posicao_final: 4, obrigatorio: true, valor_fixo: 'E200', observacoes: '' },
      { ordem: 2, nome: 'ENTRADAS OU SAÍDAS', descricao: '', tipo: 'A', tamanho: 1, decimais: null, posicao_inicial: 5, posicao_final: 5, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 3, nome: 'ESPÉCIE N.F.', descricao: '', tipo: 'X', tamanho: 5, decimais: null, posicao_inicial: 6, posicao_final: 10, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 4, nome: 'SÉRIE N.F.', descricao: '', tipo: 'X', tamanho: 3, decimais: null, posicao_inicial: 11, posicao_final: 13, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 5, nome: 'SUBSÉRIE N.F', descricao: '', tipo: 'X', tamanho: 2, decimais: null, posicao_inicial: 14, posicao_final: 15, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 6, nome: 'Nº INICIAL DA N. F.', descricao: '', tipo: 'N', tamanho: 10, decimais: null, posicao_inicial: 16, posicao_final: 25, obrigatorio: true, valor_fixo: null, observacoes: '' },
      { ordem: 7, nome: 'Nº FINAL DA N. F', descricao: '', tipo: 'N', tamanho: 10, decimais: null, posicao_inicial: 26, posicao_final: 35, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 8, nome: 'CÓDIGO DO CLIENTE/FORNECEDOR', descricao: '', tipo: 'X', tamanho: 20, decimais: null, posicao_inicial: 36, posicao_final: 55, obrigatorio: true, valor_fixo: null, observacoes: '' },
      { ordem: 9, nome: 'DATA DE EMISSÃO', descricao: '', tipo: 'D', tamanho: 8, decimais: null, posicao_inicial: 56, posicao_final: 63, obrigatorio: true, valor_fixo: null, observacoes: '' },
      { ordem: 10, nome: 'DATA DE ENTRADA/SAÍDA', descricao: '', tipo: 'D', tamanho: 8, decimais: null, posicao_inicial: 64, posicao_final: 71, obrigatorio: true, valor_fixo: null, observacoes: '' },
      { ordem: 11, nome: 'UF DA N.F.', descricao: '', tipo: 'A', tamanho: 2, decimais: null, posicao_inicial: 72, posicao_final: 73, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 12, nome: 'MODELO DA N.F.', descricao: '', tipo: 'A', tamanho: 2, decimais: null, posicao_inicial: 74, posicao_final: 75, obrigatorio: true, valor_fixo: null, observacoes: '' },
      { ordem: 13, nome: 'EMITENTE DA N.F.', descricao: '', tipo: 'A', tamanho: 1, decimais: null, posicao_inicial: 76, posicao_final: 76, obrigatorio: true, valor_fixo: null, observacoes: '' },
      { ordem: 14, nome: 'SITUAÇÃO DA N.F.', descricao: '', tipo: 'N', tamanho: 2, decimais: null, posicao_inicial: 77, posicao_final: 78, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 15, nome: 'JUSTIFICATIVA NF CANCELADA', descricao: '', tipo: 'X', tamanho: 254, decimais: null, posicao_inicial: 79, posicao_final: 332, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 16, nome: 'HORA DA EMISSÃO DA N.F. (REDF)', descricao: '', tipo: 'N', tamanho: 6, decimais: null, posicao_inicial: 333, posicao_final: 338, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 17, nome: 'HORA DA ENTRADA/SAÍDA DA N.F. (REDF)', descricao: '', tipo: 'N', tamanho: 6, decimais: null, posicao_inicial: 339, posicao_final: 344, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 18, nome: 'TIPO DO FRETE', descricao: '', tipo: 'N', tamanho: 1, decimais: null, posicao_inicial: 345, posicao_final: 345, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 19, nome: 'VALOR CONTÁBIL', descricao: '', tipo: 'N', tamanho: 14, decimais: 2, posicao_inicial: 346, posicao_final: 359, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 20, nome: 'CÓD. INT. CONTÁBIL IMPOSTOS RETIDOS', descricao: '', tipo: 'A', tamanho: 2, decimais: null, posicao_inicial: 360, posicao_final: 361, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 21, nome: 'CÓDIGO DA CONTA', descricao: '', tipo: 'X', tamanho: 50, decimais: null, posicao_inicial: 362, posicao_final: 411, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 22, nome: 'NF CONJUGADA', descricao: '', tipo: 'A', tamanho: 1, decimais: null, posicao_inicial: 412, posicao_final: 412, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 23, nome: 'Nº LINHAS DE LANÇAMENTO', descricao: '', tipo: 'N', tamanho: 2, decimais: null, posicao_inicial: 413, posicao_final: 414, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 24, nome: 'DATA DE LANÇAMENTO NO SISTEMA', descricao: '', tipo: 'D', tamanho: 8, decimais: null, posicao_inicial: 415, posicao_final: 422, obrigatorio: true, valor_fixo: null, observacoes: '' },
    ],
  },
  E201: {
    registro: 'E201',
    descricao: 'LANÇAMENTOS DE IMPOSTOS DAS NOTAS FISCAIS',
    obrigatorio: false,
    ocorrencia: 'um por CFOP/alíquota da nota',
    descricao_geral: 'Lançamento de impostos da nota fiscal. Tamanho fixo 284.',
    campos: [
      { ordem: 1, nome: 'NOME DO REGISTRO', descricao: '', tipo: 'A', tamanho: 4, decimais: null, posicao_inicial: 1, posicao_final: 4, obrigatorio: true, valor_fixo: 'E201', observacoes: '' },
      { ordem: 2, nome: 'ENTRADAS OU SAÍDAS', descricao: '', tipo: 'A', tamanho: 1, decimais: null, posicao_inicial: 5, posicao_final: 5, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 3, nome: 'ESPÉCIE N.F.', descricao: '', tipo: 'X', tamanho: 5, decimais: null, posicao_inicial: 6, posicao_final: 10, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 4, nome: 'SÉRIE N.F', descricao: '', tipo: 'X', tamanho: 3, decimais: null, posicao_inicial: 11, posicao_final: 13, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 5, nome: 'SUBSÉRIE N.F', descricao: '', tipo: 'X', tamanho: 2, decimais: null, posicao_inicial: 14, posicao_final: 15, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 6, nome: 'NÚMERO N.F.', descricao: '', tipo: 'N', tamanho: 10, decimais: null, posicao_inicial: 16, posicao_final: 25, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 7, nome: 'CÓDIGO DO CLIENTE/FORNECEDOR', descricao: '', tipo: 'X', tamanho: 20, decimais: null, posicao_inicial: 26, posicao_final: 45, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 8, nome: 'CFOP', descricao: '', tipo: 'N', tamanho: 4, decimais: null, posicao_inicial: 46, posicao_final: 49, obrigatorio: true, valor_fixo: null, observacoes: '' },
      { ordem: 9, nome: 'C.I.', descricao: '', tipo: 'A', tamanho: 2, decimais: null, posicao_inicial: 50, posicao_final: 51, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 10, nome: 'TIPO DE PAGAMENTO', descricao: '', tipo: 'N', tamanho: 1, decimais: null, posicao_inicial: 52, posicao_final: 52, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 11, nome: 'BC ICMS', descricao: '', tipo: 'N', tamanho: 14, decimais: 2, posicao_inicial: 53, posicao_final: 66, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 12, nome: 'CÓDIGO TURBO', descricao: '', tipo: 'N', tamanho: 3, decimais: null, posicao_inicial: 67, posicao_final: 69, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 13, nome: 'REDUÇÃO BASE CÁLC. ICMS', descricao: '', tipo: 'N', tamanho: 6, decimais: 3, posicao_inicial: 70, posicao_final: 75, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 14, nome: 'ALÍQUOTA DO ICMS', descricao: '', tipo: 'N', tamanho: 7, decimais: 4, posicao_inicial: 76, posicao_final: 82, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 15, nome: 'VALOR DO ICMS', descricao: '', tipo: 'N', tamanho: 14, decimais: 2, posicao_inicial: 83, posicao_final: 96, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 16, nome: 'ISENTOS DE ICMS', descricao: '', tipo: 'N', tamanho: 14, decimais: 2, posicao_inicial: 97, posicao_final: 110, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 17, nome: 'OUTRAS DE ICMS', descricao: '', tipo: 'N', tamanho: 14, decimais: 2, posicao_inicial: 111, posicao_final: 124, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 18, nome: 'ICMS SUBST. TRIB.', descricao: '', tipo: 'N', tamanho: 14, decimais: 2, posicao_inicial: 125, posicao_final: 138, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 19, nome: 'BASE SUBST. TRIB.', descricao: '', tipo: 'N', tamanho: 14, decimais: 2, posicao_inicial: 139, posicao_final: 152, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 20, nome: 'BC IPI', descricao: '', tipo: 'N', tamanho: 14, decimais: 2, posicao_inicial: 153, posicao_final: 166, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 21, nome: 'CÓDIGO TURBO P/ IPI', descricao: '', tipo: 'A', tamanho: 1, decimais: null, posicao_inicial: 167, posicao_final: 167, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 22, nome: 'VALOR DO IPI', descricao: '', tipo: 'N', tamanho: 14, decimais: 2, posicao_inicial: 168, posicao_final: 181, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 23, nome: 'ISENTOS DE IPI', descricao: '', tipo: 'N', tamanho: 14, decimais: 2, posicao_inicial: 182, posicao_final: 195, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 24, nome: 'OUTRAS DE IPI', descricao: '', tipo: 'N', tamanho: 14, decimais: 2, posicao_inicial: 196, posicao_final: 209, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 25, nome: 'CONTRIBUINTE DO ICMS', descricao: '', tipo: 'A', tamanho: 1, decimais: null, posicao_inicial: 210, posicao_final: 210, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 26, nome: 'OBSERVAÇÃO DA LINHA DE LANÇAMENTO', descricao: '', tipo: 'X', tamanho: 30, decimais: null, posicao_inicial: 211, posicao_final: 240, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 27, nome: 'Nº SEQUENCIAL DO LANÇAMENTO', descricao: '', tipo: 'N', tamanho: 2, decimais: null, posicao_inicial: 241, posicao_final: 242, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 28, nome: 'TIPO DE ANTECIPAÇÃO TRIBUTÁRIA', descricao: '', tipo: 'A', tamanho: 1, decimais: null, posicao_inicial: 243, posicao_final: 243, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 29, nome: 'ANULAÇÃO DE SERVIÇO DE TRANSPORTE', descricao: '', tipo: 'A', tamanho: 1, decimais: null, posicao_inicial: 244, posicao_final: 244, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 30, nome: 'APURAÇÕES DISTINTAS DO IPI', descricao: '', tipo: 'A', tamanho: 1, decimais: null, posicao_inicial: 245, posicao_final: 245, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 31, nome: 'VALOR A SER DEDUZIDO DA BASE DE CÁLC. PIS/COFINS (NF ENTRADAS)', descricao: '', tipo: 'N', tamanho: 14, decimais: 2, posicao_inicial: 246, posicao_final: 259, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 32, nome: 'EXCLUÍDAS (RS)', descricao: '', tipo: 'N', tamanho: 14, decimais: 2, posicao_inicial: 260, posicao_final: 273, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 33, nome: 'VENDA P/ ENTREGA FUTURA', descricao: '', tipo: 'A', tamanho: 1, decimais: null, posicao_inicial: 274, posicao_final: 274, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 34, nome: 'OPERAÇÕES SUBST TRIB SAÍDAS', descricao: '', tipo: 'A', tamanho: 1, decimais: null, posicao_inicial: 275, posicao_final: 275, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 35, nome: 'NÚMERO DO TOTALIZADOR', descricao: '', tipo: 'A', tamanho: 2, decimais: null, posicao_inicial: 276, posicao_final: 277, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 36, nome: 'SIT.TRIB. ICMS TAB. A', descricao: '', tipo: 'A', tamanho: 1, decimais: null, posicao_inicial: 278, posicao_final: 278, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 37, nome: 'SIT. TRIB. ICMS TAB. B', descricao: '', tipo: 'A', tamanho: 2, decimais: null, posicao_inicial: 279, posicao_final: 280, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 38, nome: 'SIT. TRIB. IPI', descricao: '', tipo: 'A', tamanho: 2, decimais: null, posicao_inicial: 281, posicao_final: 282, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 39, nome: 'CIAP SAÍDA TRIBUTADA', descricao: '', tipo: 'A', tamanho: 1, decimais: null, posicao_inicial: 283, posicao_final: 283, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 40, nome: 'CONTROLE DO SISTEMA', descricao: 'Informe 0', tipo: 'N', tamanho: 1, decimais: null, posicao_inicial: 284, posicao_final: 284, obrigatorio: true, valor_fixo: null, observacoes: '' },
    ],
  },
  E221: {
    registro: 'E221',
    descricao: 'CHAVE DO LANÇAMENTO DE PRODUTOS/SERVIÇOS',
    obrigatorio: false,
    ocorrencia: 'um por nota fiscal',
    descricao_geral: 'Cabeçalho de produtos da nota. Tamanho fixo 340.',
    campos: [
      { ordem: 1, nome: 'NOME DO REGISTRO', descricao: '', tipo: 'A', tamanho: 4, decimais: null, posicao_inicial: 1, posicao_final: 4, obrigatorio: true, valor_fixo: 'E221', observacoes: '' },
      { ordem: 2, nome: 'ENTRADAS OU SAÍDAS', descricao: '', tipo: 'A', tamanho: 1, decimais: null, posicao_inicial: 5, posicao_final: 5, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 3, nome: 'ESPÉCIE N.F.', descricao: '', tipo: 'X', tamanho: 5, decimais: null, posicao_inicial: 6, posicao_final: 10, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 4, nome: 'SÉRIE N.F.', descricao: '', tipo: 'X', tamanho: 3, decimais: null, posicao_inicial: 11, posicao_final: 13, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 5, nome: 'SUBSÉRIE N.F.', descricao: '', tipo: 'X', tamanho: 2, decimais: null, posicao_inicial: 14, posicao_final: 15, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 6, nome: 'NÚMERO N.F.', descricao: '', tipo: 'N', tamanho: 10, decimais: null, posicao_inicial: 16, posicao_final: 25, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 7, nome: 'CÓDIGO DO CLIENTE/FORNECEDOR', descricao: '', tipo: 'X', tamanho: 20, decimais: null, posicao_inicial: 26, posicao_final: 45, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 8, nome: 'FRETE', descricao: '', tipo: 'N', tamanho: 14, decimais: 2, posicao_inicial: 46, posicao_final: 59, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 9, nome: 'SEGURO', descricao: '', tipo: 'N', tamanho: 14, decimais: 2, posicao_inicial: 60, posicao_final: 73, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 10, nome: 'DESPESAS ACESSÓRIAS', descricao: '', tipo: 'N', tamanho: 14, decimais: 2, posicao_inicial: 74, posicao_final: 87, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 11, nome: 'QUANTIDADE DE ITENS DA N.F.', descricao: '', tipo: 'N', tamanho: 5, decimais: null, posicao_inicial: 88, posicao_final: 92, obrigatorio: true, valor_fixo: null, observacoes: '' },
      { ordem: 12, nome: 'PIS/COFINS', descricao: '', tipo: 'N', tamanho: 14, decimais: 2, posicao_inicial: 93, posicao_final: 106, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 13, nome: 'PESO BRUTO', descricao: '', tipo: 'N', tamanho: 13, decimais: 3, posicao_inicial: 107, posicao_final: 119, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 14, nome: 'PESO LÍQUIDO', descricao: '', tipo: 'N', tamanho: 13, decimais: 3, posicao_inicial: 120, posicao_final: 132, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 15, nome: 'VIA DE TRANSPORTE', descricao: '', tipo: 'N', tamanho: 1, decimais: null, posicao_inicial: 133, posicao_final: 133, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 16, nome: 'CÓDIGO DO TRANSPORTADOR', descricao: '', tipo: 'X', tamanho: 20, decimais: null, posicao_inicial: 134, posicao_final: 153, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 17, nome: 'IDENTIFICAÇÃO DO VEÍCULO (PLACA 1)', descricao: '', tipo: 'X', tamanho: 15, decimais: null, posicao_inicial: 154, posicao_final: 168, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 18, nome: 'I.E. DO SUBSTITUTO TRIBUTÁRIO', descricao: '', tipo: 'X', tamanho: 18, decimais: null, posicao_inicial: 169, posicao_final: 186, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 19, nome: 'QTDE DE VOLUMES', descricao: '', tipo: 'N', tamanho: 15, decimais: null, posicao_inicial: 187, posicao_final: 201, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 20, nome: 'ESPÉCIE DOS VOLUMES', descricao: '', tipo: 'X', tamanho: 10, decimais: null, posicao_inicial: 202, posicao_final: 211, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 21, nome: 'I.E. DO TRANSPORTADOR', descricao: '', tipo: 'A', tamanho: 18, decimais: null, posicao_inicial: 212, posicao_final: 229, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 22, nome: 'ESTADO DO TRANSPORTADOR', descricao: '', tipo: 'A', tamanho: 2, decimais: null, posicao_inicial: 230, posicao_final: 231, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 23, nome: 'ESTADO DA PLACA DO VEÍCULO (PLACA 1)', descricao: '', tipo: 'A', tamanho: 2, decimais: null, posicao_inicial: 232, posicao_final: 233, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 24, nome: 'IDENTIFICAÇÃO DO VEÍCULO (PLACA 2)', descricao: '', tipo: 'X', tamanho: 15, decimais: null, posicao_inicial: 234, posicao_final: 248, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 25, nome: 'ESTADO DA PLACA DO VEÍCULO (PLACA 2)', descricao: '', tipo: 'A', tamanho: 2, decimais: null, posicao_inicial: 249, posicao_final: 250, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 26, nome: 'IDENTIFICAÇÃO DO VEÍCULO (PLACA 3)', descricao: '', tipo: 'X', tamanho: 15, decimais: null, posicao_inicial: 251, posicao_final: 265, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 27, nome: 'ESTADO DA PLACA DO VEÍCULO (PLACA 3)', descricao: '', tipo: 'A', tamanho: 2, decimais: null, posicao_inicial: 266, posicao_final: 267, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 28, nome: 'LOCAL DE SAÍDA DA MERCADORIA', descricao: '', tipo: 'N', tamanho: 1, decimais: null, posicao_inicial: 268, posicao_final: 268, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 29, nome: 'CNPJ/CPF DA SAÍDA DA MERCADORIA', descricao: '', tipo: 'A', tamanho: 14, decimais: null, posicao_inicial: 269, posicao_final: 282, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 30, nome: 'ESTADO DA SAÍDA DA MERCADORIA', descricao: '', tipo: 'A', tamanho: 2, decimais: null, posicao_inicial: 283, posicao_final: 284, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 31, nome: 'I.E. DA SAÍDA DA MERCADORIA', descricao: '', tipo: 'A', tamanho: 18, decimais: null, posicao_inicial: 285, posicao_final: 302, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 32, nome: 'LOCAL DE RECEBIMENTO DA MERCADORIA', descricao: '', tipo: 'N', tamanho: 1, decimais: null, posicao_inicial: 303, posicao_final: 303, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 33, nome: 'CNPJ/CPF DO RECEBIMENTO DA MERCADORIA', descricao: '', tipo: 'A', tamanho: 14, decimais: null, posicao_inicial: 304, posicao_final: 317, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 34, nome: 'ESTADO DO RECEBIMENTO DA MERCADORIA', descricao: '', tipo: 'A', tamanho: 2, decimais: null, posicao_inicial: 318, posicao_final: 319, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 35, nome: 'I.E. DO RECEBIMENTO DA MERCADORIA', descricao: '', tipo: 'A', tamanho: 18, decimais: null, posicao_inicial: 320, posicao_final: 337, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 36, nome: 'UF DO TRANSPORTADOR', descricao: '', tipo: 'A', tamanho: 2, decimais: null, posicao_inicial: 338, posicao_final: 339, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 37, nome: 'CONTROLE DO SISTEMA', descricao: 'Informe 0', tipo: 'N', tamanho: 1, decimais: null, posicao_inicial: 340, posicao_final: 340, obrigatorio: true, valor_fixo: null, observacoes: '' },
    ],
  },
  E222: {
    registro: 'E222',
    descricao: 'LANÇAMENTO DE PRODUTOS/SERVIÇOS',
    obrigatorio: false,
    ocorrencia: 'um por item da nota',
    descricao_geral: 'Item/produto da nota fiscal. Tamanho fixo 594.',
    campos: [
      { ordem: 1, nome: 'NOME DO REGISTRO', descricao: '', tipo: 'A', tamanho: 4, decimais: null, posicao_inicial: 1, posicao_final: 4, obrigatorio: true, valor_fixo: 'E222', observacoes: '' },
      { ordem: 2, nome: 'ENTRADAS OU SAÍDAS', descricao: '', tipo: 'A', tamanho: 1, decimais: null, posicao_inicial: 5, posicao_final: 5, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 3, nome: 'ESPÉCIE N.F.', descricao: '', tipo: 'X', tamanho: 5, decimais: null, posicao_inicial: 6, posicao_final: 10, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 4, nome: 'SÉRIE N.F.', descricao: '', tipo: 'X', tamanho: 3, decimais: null, posicao_inicial: 11, posicao_final: 13, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 5, nome: 'SUBSÉRIE N.F.', descricao: '', tipo: 'X', tamanho: 2, decimais: null, posicao_inicial: 14, posicao_final: 15, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 6, nome: 'NÚMERO N.F.', descricao: '', tipo: 'N', tamanho: 10, decimais: null, posicao_inicial: 16, posicao_final: 25, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 7, nome: 'CÓDIGO DO CLIENTE/FORNECEDOR', descricao: '', tipo: 'X', tamanho: 20, decimais: null, posicao_inicial: 26, posicao_final: 45, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 8, nome: 'Nº ITEM', descricao: '', tipo: 'N', tamanho: 3, decimais: null, posicao_inicial: 46, posicao_final: 48, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 9, nome: 'CFOP', descricao: '', tipo: 'A', tamanho: 4, decimais: null, posicao_inicial: 49, posicao_final: 52, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 10, nome: 'CÓDIGO DO PRODUTO/SERVIÇO', descricao: '', tipo: 'X', tamanho: 14, decimais: null, posicao_inicial: 53, posicao_final: 66, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 11, nome: 'ALÍQUOTA DO ICMS', descricao: '', tipo: 'N', tamanho: 7, decimais: 4, posicao_inicial: 67, posicao_final: 73, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 12, nome: 'QUANTIDADE', descricao: '', tipo: 'N', tamanho: 15, decimais: 5, posicao_inicial: 74, posicao_final: 88, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 13, nome: 'VLR.MERCADORIA/SERVIÇO', descricao: '', tipo: 'N', tamanho: 14, decimais: 2, posicao_inicial: 89, posicao_final: 102, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 14, nome: 'VALOR DO DESCONTO', descricao: '', tipo: 'N', tamanho: 14, decimais: 2, posicao_inicial: 103, posicao_final: 116, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 15, nome: 'BASE DE CÁLCULO DO ICMS', descricao: '', tipo: 'N', tamanho: 14, decimais: 2, posicao_inicial: 117, posicao_final: 130, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 16, nome: 'BASE SUBST. TRIB.', descricao: '', tipo: 'N', tamanho: 14, decimais: 2, posicao_inicial: 131, posicao_final: 144, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 17, nome: 'VALOR DO IPI', descricao: '', tipo: 'N', tamanho: 14, decimais: 2, posicao_inicial: 145, posicao_final: 158, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 18, nome: 'VALOR UNITÁRIO', descricao: '', tipo: 'N', tamanho: 14, decimais: 4, posicao_inicial: 159, posicao_final: 172, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 19, nome: 'NÚMERO DI / DSI', descricao: '', tipo: 'N', tamanho: 10, decimais: null, posicao_inicial: 173, posicao_final: 182, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 20, nome: 'BC DO IPI', descricao: '', tipo: 'N', tamanho: 14, decimais: 2, posicao_inicial: 183, posicao_final: 196, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 21, nome: 'VALOR DO ICMS', descricao: '', tipo: 'N', tamanho: 14, decimais: 2, posicao_inicial: 197, posicao_final: 210, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 22, nome: 'ISENTOS DE ICMS', descricao: '', tipo: 'N', tamanho: 14, decimais: 2, posicao_inicial: 211, posicao_final: 224, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 23, nome: 'OUTROS DE ICMS', descricao: '', tipo: 'N', tamanho: 14, decimais: 2, posicao_inicial: 225, posicao_final: 238, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 24, nome: 'Nº COO', descricao: '', tipo: 'N', tamanho: 10, decimais: null, posicao_inicial: 239, posicao_final: 248, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 25, nome: 'ICMS SUBST. TRIB.', descricao: '', tipo: 'N', tamanho: 14, decimais: 2, posicao_inicial: 249, posicao_final: 262, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 26, nome: 'MOVIMENTAÇÃO FÍSICA DA MERCADORIA', descricao: '', tipo: 'A', tamanho: 1, decimais: null, posicao_inicial: 263, posicao_final: 263, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 27, nome: 'ISENTOS DE IPI', descricao: '', tipo: 'N', tamanho: 14, decimais: 2, posicao_inicial: 264, posicao_final: 277, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 28, nome: 'OUTROS DE IPI', descricao: '', tipo: 'N', tamanho: 14, decimais: 2, posicao_inicial: 278, posicao_final: 291, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 29, nome: 'BASE ST NA ORIGEM/DESTINO', descricao: '', tipo: 'N', tamanho: 14, decimais: 2, posicao_inicial: 292, posicao_final: 305, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 30, nome: 'ICMS-ST A REPASSAR', descricao: '', tipo: 'N', tamanho: 14, decimais: 2, posicao_inicial: 306, posicao_final: 319, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 31, nome: 'ICMS-ST A COMPLEMENTAR', descricao: '', tipo: 'N', tamanho: 14, decimais: 2, posicao_inicial: 320, posicao_final: 333, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 32, nome: 'ITEM CANCELADO', descricao: '', tipo: 'A', tamanho: 1, decimais: null, posicao_inicial: 334, posicao_final: 334, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 33, nome: 'OPERAÇÕES SUBST TRIB SAÍDAS ITEM', descricao: '', tipo: 'A', tamanho: 1, decimais: null, posicao_inicial: 335, posicao_final: 335, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 34, nome: 'ISS', descricao: '', tipo: 'A', tamanho: 1, decimais: null, posicao_inicial: 336, posicao_final: 336, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 35, nome: 'CÓDIGO UNID. COMERCIAL', descricao: '', tipo: 'X', tamanho: 6, decimais: null, posicao_inicial: 337, posicao_final: 342, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 36, nome: 'CÓDIGO DA NATUREZA DA OPERAÇÃO', descricao: '', tipo: 'X', tamanho: 10, decimais: null, posicao_inicial: 343, posicao_final: 352, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 37, nome: 'DESCRIÇÃO COMPLEMENTAR DO PRODUTO', descricao: '', tipo: 'X', tamanho: 50, decimais: null, posicao_inicial: 353, posicao_final: 402, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 38, nome: 'FATOR DE CONVERSÃO', descricao: '', tipo: 'N', tamanho: 14, decimais: 6, posicao_inicial: 403, posicao_final: 416, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 39, nome: 'ALÍQUOTA DO ICMS S.T.', descricao: '', tipo: 'N', tamanho: 6, decimais: 2, posicao_inicial: 417, posicao_final: 422, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 40, nome: 'SIT.TRIB. ICMS TAB. A', descricao: '', tipo: 'A', tamanho: 1, decimais: null, posicao_inicial: 423, posicao_final: 423, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 41, nome: 'SIT.TRIB. ICMS TAB. B', descricao: '', tipo: 'A', tamanho: 2, decimais: null, posicao_inicial: 424, posicao_final: 425, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 42, nome: 'SIT. TRIB. IPI', descricao: '', tipo: 'A', tamanho: 2, decimais: null, posicao_inicial: 426, posicao_final: 427, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 43, nome: 'APURAÇÃO DISTINTAS DO IPI', descricao: '', tipo: 'A', tamanho: 1, decimais: null, posicao_inicial: 428, posicao_final: 428, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 44, nome: 'CÓDIGO DA CONTA', descricao: '', tipo: 'X', tamanho: 50, decimais: null, posicao_inicial: 429, posicao_final: 478, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 45, nome: 'FRETE ITEM', descricao: '', tipo: 'N', tamanho: 14, decimais: 2, posicao_inicial: 479, posicao_final: 492, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 46, nome: 'FRETE NO TOTAL DA NF', descricao: '', tipo: 'A', tamanho: 1, decimais: null, posicao_inicial: 493, posicao_final: 493, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 47, nome: 'SEGURO ITEM', descricao: '', tipo: 'N', tamanho: 14, decimais: 2, posicao_inicial: 494, posicao_final: 507, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 48, nome: 'SEGURO NO TOTAL DA NF', descricao: '', tipo: 'A', tamanho: 1, decimais: null, posicao_inicial: 508, posicao_final: 508, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 49, nome: 'DESPESAS ACESSÓRIAS ITEM', descricao: '', tipo: 'N', tamanho: 14, decimais: 2, posicao_inicial: 509, posicao_final: 522, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 50, nome: 'DESPESAS ACESSÓRIAS NO TOTAL DA NF', descricao: '', tipo: 'A', tamanho: 1, decimais: null, posicao_inicial: 523, posicao_final: 523, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 51, nome: 'ACRÉSCIMO', descricao: '', tipo: 'N', tamanho: 14, decimais: 2, posicao_inicial: 524, posicao_final: 537, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 52, nome: 'REDUÇÃO BASE CÁLC. ICMS ITEM', descricao: '', tipo: 'N', tamanho: 7, decimais: 4, posicao_inicial: 538, posicao_final: 544, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 53, nome: 'VALOR NÃO TRIBUTADO RED BC ICMS', descricao: '', tipo: 'N', tamanho: 14, decimais: 2, posicao_inicial: 545, posicao_final: 558, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 54, nome: 'QUANTIDADE CANCELADA', descricao: '', tipo: 'N', tamanho: 14, decimais: 3, posicao_inicial: 559, posicao_final: 572, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 55, nome: 'BASE ICMS REDUZIDA', descricao: '', tipo: 'N', tamanho: 14, decimais: 2, posicao_inicial: 573, posicao_final: 586, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 56, nome: 'DADOS PARA REDF NF PAULISTA', descricao: '', tipo: 'N', tamanho: 1, decimais: null, posicao_inicial: 587, posicao_final: 587, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 57, nome: 'NÚMERO DO TOTALIZADOR ITEM', descricao: '', tipo: 'A', tamanho: 2, decimais: null, posicao_inicial: 588, posicao_final: 589, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 58, nome: 'DESCONTO INCONDICIONAL', descricao: '', tipo: 'A', tamanho: 1, decimais: null, posicao_inicial: 590, posicao_final: 590, obrigatorio: true, valor_fixo: null, observacoes: '' },
      { ordem: 59, nome: 'CSOSN', descricao: '', tipo: 'A', tamanho: 3, decimais: null, posicao_inicial: 591, posicao_final: 593, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 60, nome: 'CONTROLE DO SISTEMA', descricao: 'Informe 0', tipo: 'N', tamanho: 1, decimais: null, posicao_inicial: 594, posicao_final: 594, obrigatorio: true, valor_fixo: null, observacoes: '' },
    ],
  },
  E342: {
    registro: 'E342',
    descricao: 'CHAVE DA NF-E/NFC-E/CT-E/CF-E',
    obrigatorio: false,
    ocorrencia: 'um por nota fiscal eletrônica',
    descricao_geral: 'Chave de acesso de NF-e/NFC-e/CT-e/CF-e. Tamanho fixo 135.',
    campos: [
      { ordem: 1, nome: 'NOME DO REGISTRO', descricao: '', tipo: 'A', tamanho: 4, decimais: null, posicao_inicial: 1, posicao_final: 4, obrigatorio: true, valor_fixo: 'E342', observacoes: '' },
      { ordem: 2, nome: 'ENTRADAS OU SAÍDAS', descricao: '', tipo: 'A', tamanho: 1, decimais: null, posicao_inicial: 5, posicao_final: 5, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 3, nome: 'ESPÉCIE N.F.', descricao: '', tipo: 'X', tamanho: 5, decimais: null, posicao_inicial: 6, posicao_final: 10, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 4, nome: 'SÉRIE N.F.', descricao: '', tipo: 'X', tamanho: 3, decimais: null, posicao_inicial: 11, posicao_final: 13, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 5, nome: 'SUBSÉRIE N.F.', descricao: '', tipo: 'X', tamanho: 2, decimais: null, posicao_inicial: 14, posicao_final: 15, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 6, nome: 'NÚMERO N.F.', descricao: '', tipo: 'N', tamanho: 10, decimais: null, posicao_inicial: 16, posicao_final: 25, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 7, nome: 'CÓDIGO DO CLIENTE', descricao: '', tipo: 'X', tamanho: 20, decimais: null, posicao_inicial: 26, posicao_final: 45, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 8, nome: 'CHAVE DA NF-E/CT-E/CF-E/NFC-E', descricao: '', tipo: 'A', tamanho: 44, decimais: null, posicao_inicial: 46, posicao_final: 89, obrigatorio: true, valor_fixo: null, observacoes: '' },
      { ordem: 9, nome: 'TIPO DE CT-e', descricao: '', tipo: 'A', tamanho: 1, decimais: null, posicao_inicial: 90, posicao_final: 90, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 10, nome: 'CHAVE DO CT-e DE REFERÊNCIA', descricao: '', tipo: 'A', tamanho: 44, decimais: null, posicao_inicial: 91, posicao_final: 134, obrigatorio: false, valor_fixo: null, observacoes: '' },
      { ordem: 11, nome: 'CONTROLE DO SISTEMA', descricao: 'Informe 0', tipo: 'N', tamanho: 1, decimais: null, posicao_inicial: 135, posicao_final: 135, obrigatorio: true, valor_fixo: null, observacoes: '' },
    ],
  },
};
